# REFERENCE: https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md
unstable_features = true
comment_width = 100
wrap_comments = true
format_strings = true
imports_indent = "Block"
imports_layout = "Mixed"
newline_style = "Unix"
normalize_comments = true
