# REFERENCE: https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md
unstable_features = true
indent_style = "Block"
use_small_heuristics = true
binop_separator = "Front"
combine_control_expr = true
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
max_width = 100
error_on_line_overflow = true
comment_width = 100
wrap_comments = true
fn_args_density = "Tall"
brace_style = "SameLineWhere"
empty_item_single_line = true
fn_single_line = false
where_single_line = false
force_explicit_abi = true
format_strings = true
hard_tabs = false
imports_indent = "Visual"
imports_layout = "Mixed"
match_block_trailing_comma = false
merge_derives = true
force_multiline_blocks = false
newline_style = "Unix"
normalize_comments = true
reorder_imports = true
report_todo = "Never"
report_fixme = "Never"
space_after_colon = true
skip_children = false
space_before_colon = false
struct_field_align_threshold = 0
spaces_around_ranges = false
spaces_within_parens_and_brackets = false
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_try_shorthand = false
match_arm_blocks = true
write_mode = "Overwrite"
